return {
  ["workshop-1383795736"]={ configuration_options={  }, enabled=true },
  ["workshop-2032685784"]={ configuration_options={  }, enabled=true },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2
    },
    enabled=true
  },
  ["workshop-407977022"]={
    configuration_options={
      [""]=1,
      afester_config=true,
      bluester_config=true,
      cavester_config=true,
      chilltime=0.5,
      daddy_config=true,
      dubster_config=true,
      force_afester=false,
      force_bluester=false,
      force_daddy=false,
      force_dubster=false,
      force_stovester=false,
      stovester_config=true 
    },
    enabled=true 
  },
  ["workshop-438293817"]={ configuration_options={  }, enabled=true },
  ["workshop-458940297"]={
    configuration_options={
      DFV_ClientPrediction="default",
      DFV_FueledSettings="default",
      DFV_Language="EN",
      DFV_MinimalMode="default",
      DFV_PercentReplace="default",
      DFV_ShowACondition="default",
      DFV_ShowADefence="default",
      DFV_ShowAType="default",
      DFV_ShowDamage="default",
      DFV_ShowFireTime="default",
      DFV_ShowInsulation="default",
      DFV_ShowTemperature="default",
      DFV_ShowUses="default" 
    },
    enabled=true 
  },
  ["workshop-463740026"]={ configuration_options={ ownership=false }, enabled=true },
  ["workshop-478005098"]={ configuration_options={  }, enabled=true },
  ["workshop-551324730"]={ configuration_options={  }, enabled=true },
  ["workshop-569043634"]={
    configuration_options={
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      KillMe="Unchanged",
      NoPlayerSkeletons="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged" 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  } 
}
